#version
version: "3"

#liste des containers
services:
  #conteneur mariadb
  mariadb:
    #nom
    container_name: mariadb
    #image name
    image: mariadb
    #emplacement du fichier environnement
    env_file:
      - .env
    #emplacement dockerfile
    build:
      #directory
      context: ./requirements/mariadb/.
      #dockerfile name
      dockerfile: ./Dockerfile
      #arguments a passer
      args:
       - SQL_DATABASE=${SQL_DATABASE}
       - SQL_USER=${SQL_USER}
       - SQL_PASSWORD=${SQL_PASSWORD}
       - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
       - WP_ADMIN=${WP_ADMIN}
       - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
    #emplacement des volumes
    volumes:
      - mariadb:/var/lib/mysql
    #le numero du port
    ports:
      - "3306"
    #type de redemarrage
    restart: unless-stopped #tant que non stopper
    #network d'appartenance
    networks:
      - inception

  wordpress:
    #dependances (les container sous cette options sont neecessaire avant le demarage de ce container)
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    build:
      context: ./requirements/wordpress/.
      dockerfile: ./Dockerfile
      args:
       - SQL_DATABASE=${SQL_DATABASE}
       - SQL_USER=${SQL_USER}
       - SQL_PASSWORD=${SQL_PASSWORD}
       - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
       - SQL_HOST=${SQL_HOST}
       - WP_URL=${WP_URL}
       - WP_TITLE=${WP_TITLE}
       - WP_ADMIN=${WP_ADMIN}
       - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
       - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
       - WP_USR=${WP_USR}
       - WP_USR_MAIL=${WP_USR_MAIL}
       - WP_USR_PASS=${WP_USR_PASS}
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "9000"
    restart: on-failure #uniquement en cas de crash
    networks:
      - inception

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    env_file:
      - .env
    build:
      context: ./requirements/nginx/.
      dockerfile: ./Dockerfile
    volumes: 
      - wordpress:/var/www/wordpress
    # port exposee a la machine locale
    ports: 
      - "443:443"
    restart: on-failure
    networks:
      - inception

#listes des volumes de stockage
volumes:
  #nom du conteneur de stockage
  wordpress:
    #nom du volume
    name: 'wordpress'
    #type du volume (local)
    driver: local
    driver_opts:
      #type de volume (si specigique)
      type: 'none'
      o: 'bind'
      #l'adresse de stockage
      device: '~/data/wordpress'

  mariadb:
    name: 'mariadb'
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '~/data/mariadb'

#reglage du network
networks:
  #nom du network
  inception:
    #nom du network
    name: inception
    #type de driver
    driver: bridge
